# Generated by Django 4.2.5 on 2023-09-12 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('date_attempts', models.DateTimeField(auto_now_add=True, verbose_name='дата попытки')),
                ('status', models.CharField(max_length=100, verbose_name='статус попытки')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'cообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.DateTimeField(auto_now_add=True, verbose_name='время рассылки')),
                ('frequency', models.PositiveSmallIntegerField(choices=[(1, 'Раз в день'), (2, 'Раз в неделю'), (3, 'Раз в месяц')], default=1, verbose_name='переодичность рассылки')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Создана'), (2, 'Запущена'), (3, 'Завершена')], default=1, verbose_name='статус рассылки')),
                ('massage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.massage', verbose_name='cообщение')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
