# Generated by Django 4.2.5 on 2023-09-13 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_rename_massage_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='рассылки'),
        ),
    ]
