# Generated by Django 4.2.5 on 2023-09-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('surname', models.CharField(blank=True, max_length=150, null=True, verbose_name='отчество')),
                ('comment', models.CharField(max_length=400, verbose_name='комментарий')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='контактная почта')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='активация')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
    ]
